### ISSUE TITLE
"Incorrect" unit of measurement in Home Assistant

### ISSUE THREAD

**Issue by Glenf** [akx/hass-ruuvitag#1]
Home Assistant wants to have unit_of_measurement as "°C". hass-ruuvitag provides it as "C". It does work but Homekit integration doesn't show correct temperature with "C" as unit of measurement.

**Comment by akx** [comment]
Looks like another case of the Hass docs being vähän sinnepäin.

https://developers.home-assistant.io/docs/en/entity_sensor.html#available-device-classes says:

> If specifying a device class, your sensor entity will need to also return the correct unit of measurement.
> [...]
> `temperature`: C/F

**Comment by Glenf** [comment]
Thanks, this works correctly on Homekit now. Created a PR to fix the docs on Hass end for this.

https://github.com/home-assistant/developers.home-assistant/pull/160
