### ISSUE TITLE
Ruuvitags in HA have become more and more unstable

### ISSUE THREAD

**Issue by ojalaj** [akx/hass-ruuvitag#14]
I have Hass.io running on RPi3 and I have always updated to newest releases. The addon is version 0.2.0.

With time, Ruuvitags have become more and more unstable - they lose connection once or twice a day (last reading at some time point and no new readings after that). Cure for this is usually restarting addon or rebooting hass.io. In addon log I have e.g.:
```
noble warning: unknown handle 1196 disconnected!
noble warning: unknown handle 1205 disconnected!
noble warning: unknown handle 1191 disconnected!
```
but have also got Bad gateway 502 notifications.

Also, the readings have started getting more and more spikes in them.

Do you have any idea why this is happening and what might help?

**Comment by ojalaj** [comment]
The problem seems to be solved (I’ve got flawless data - no interruptions, no spikes - for more than week now) with these steps:

- Buying the cheapest USB BT dongle
- I was lucky to notice that it worked out of the box
- Disabled RPi3 BT (SD card to Win10 machine, add ‘dtoverlay=pi3-disable-bt’ to the end of ‘/boot/config.txt’)
- Now the dongle is the default BT and everything works as expected (so far)

**Comment by ojalaj** [comment]
The problem seems to be solved (I’ve got flawless data - no interruptions, no spikes - for more than week now) with these steps:

- Buying the cheapest USB BT dongle
- I was lucky to notice that it worked out of the box
- Disabled RPi3 BT (SD card to Win10 machine, add ‘dtoverlay=pi3-disable-bt’ to the end of ‘/boot/config.txt’)
- Now the dongle is the default BT and everything works as expected (so far)

**Comment by akx** [comment]
Glad to hear, and thank you for the troubleshooting steps – they'll surely help someone else too.

For the record, I've moved on from the hass.io distribution on RPi – instead I'm just running regular Home Assistant on Arch Linux on an Intel NUC, and it's mostly rock stable :)
