### ISSUE TITLE
This add-on compatible with Ruuvitag FW 2.5.9?

### ISSUE THREAD

**Issue by ojalaj** [akx/hass-ruuvitag#17]
Wanted to ask before upgrading the FW:
https://lab.ruuvi.com/ruuvitag-fw/

**Comment by akx** [comment]
Yes, data format 5 should be supported in the https://github.com/akx/hass-ruuvitag/tree/ruuvidriver-0.3.0 branch (see #9).

If you're willing to kick the tires to see if that branch works with an upgraded Ruuvi, we can merge it to master. :)

**Comment by ojalaj** [comment]
OK, yes - I can test it. First I want to install 0.3.0 branch. Since I wasn't sure how to do it in hass.io GUI, I first made a back-up on command line under /root/addons/hass-ruuvitag of 0.2.0. Then I used git to checkout 0.3.0, uninstalled the add-on on GUI, then installed again. However, it still says 0.2.0 everywhere (on top rightcorner of GUI) and in the log box "This is hassio-ruuvitag 0.2.0, terrrrrrrve". 

How I can check which version I actually running?

**Comment by akx** [comment]
Ah, right, I'm sorry, I hadn't thought to update the package version in that branch. If you do the pull dance again, it should definitely be 0.3.0 now (51e66c5).

**Comment by vasarat1** [comment]
I've been testing the 0.3.0 branch today with ruuvitags updated to FW 2.5.9 and can verify that everything is working on my hass.io setup! Previous hass-ruuvitag version also worked with the new firmware, but had to revert to the RawV1 format on the tags to get sensible values out of them

**Comment by ojalaj** [comment]
@vasarat1 Great! I just two minutes ago updated to 0.3.0, with success. And now I'm about to upgrade the FW 2.5.9.

**Comment by ojalaj** [comment]
First Ruuvitag upgraded and at least I get some readings. @vasarat1 You mean that with 0.3.0 & FW 2.5.9 you can can operate all modes - RAWv1-fast, RAWv2-slow and RAWv2-fast - and get sensible readings?

**Comment by vasarat1** [comment]
Yes, with 0.3.0 the readings look sensible in both data formats and measurement rates, and match those reported by the Ruuvi Station android app. At first there appeared to be a minor offset in temp and RH between RAWv1 and v2 data in the history graph, but that evened out after a while. Most likely just a small disturbance from opening the enclosure and pushing the button with my warm fleshy finger.

With 0.2.0, the RAWv2 readings were all over the place, with e.g. temperature randomly fluctuating somewhere between -100 and +100. Is that what you're seeing?

**Comment by ojalaj** [comment]
I had no such problems with 0.2.0 and older FW. However, I had other problems unrelated to 0.2.0 (see #14 and https://f.ruuvi.com/t/ruuvitags-in-ha-more-and-more-unstable-with-time/3953/5).

**Comment by akx** [comment]
Based on this, I'd say 0.3.0 is compatible with the new firmware, so I'm going to promote it to `master`.

Thanks for testing things, folks!
