### ISSUE TITLE
Supervisor assisted addon installation fails

### ISSUE THREAD

**Issue by Nurffe** [akx/hass-ruuvitag#26]
Installation fails with following error when trying to isntall thru _supervisor -> add-on store -> Ruuvitag -> Install_

`hassio-supervisor[14820]: 20-06-19 19:11:23 ERROR (SyncWorker_3) [supervisor.docker.addon] Can't build local/armv7-addon-hello_world:1: The command '/bin/ash -o pipefail -c apk add --no-cache python build-base yarn git' returned a non-zero code: 1`

 Not sure exactly what's wrong here as command looks ok and shouldn't return 1. However I lack knowledge to debug hassio to get more verbose output whats the issue here so.. Good ideas welcome

_Running on raspi3_

- homeassistant/armv7-hassio-supervisor 227
- homeassistant/raspberrypi3-homeassistant 0.111.4

**Comment by Stude** [comment]
You need to update container to use python3 instead of python2 (which isn't supported anymore).
Required changes: https://github.com/akx/hass-ruuvitag/pull/27

**Comment by Nurffe** [comment]
Of course. That fixes the issues with docker build

Thanks :)
