### ISSUE TITLE
Readings are out of this planet

### ISSUE THREAD

**Issue by nullnullnul** [akx/hass-ruuvitag#9]
Thanks for creating the addon for us!
There seems to be some problem with the readings though, any idea why I get these kind of values out from my tags? Altough it is already september, but certainly it is not -104 degrees.
{"dataFormat":3,"rssi":-82,"humidity":7.5,"temperature":-104.61,"pressure":82195,"accelerationX":-8448,"accelerationY":1279,"accelerationZ":-4092,"battery":1199}

Using Hassos, and cloned the repository/installed as addon about 5 days ago.

**Comment by acirtautas** [comment]
I am running RuuviTag on v2 slow format and readings are really random.

![Screenshot 2019-09-24 at 11 59 57](https://user-images.githubusercontent.com/1830639/65497426-e8aa3000-dec2-11e9-9f40-769f38d5adf1.png)

HassOS 2.12

**Comment by acirtautas** [comment]
The issue is related to ruuvi format version, after resetting the sensor, I started getting propper readings (using format 3).

![Screenshot 2019-09-25 at 08 41 32](https://user-images.githubusercontent.com/1830639/65572303-56f8fc00-df70-11e9-9b17-2fde1f91773a.png)

**Comment by akx** [comment]
This should be fixed in the [`ruuvidriver-0.3.0`](https://github.com/akx/hass-ruuvitag/tree/ruuvidriver-0.3.0) branch that includes Ruuvidriver 0.3 which in kind includes support for data format v5 (thanks again @okko) – can you try with it?

**Comment by akx** [comment]
Master now supports new firmware versions, closing.
